#!/usr/bin/env python3
"""
Engineering Intelligence System - CLI Wrapper

Simplifies running the project without 'uv run' prefix.
Automatically detects and uses the virtual environment.
"""

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
VENV_PYTHON = PROJECT_ROOT / ".venv" / "bin" / "python"
UV = "uv"


def get_python():
    """Get Python executable from venv or fall back to system."""
    if VENV_PYTHON.exists():
        return str(VENV_PYTHON)
    return sys.executable


def run_command(cmd, use_uv=False, capture=False):
    """Run a command with the appropriate Python."""
    env = os.environ.copy()
    env.pop("PYTHONPATH", None)

    if use_uv:
        result = subprocess.run(
            [UV, "run", "python", "-c", cmd]
            if cmd.startswith("import")
            else [UV, "run"] + cmd.split(),
            cwd=PROJECT_ROOT,
            env=env,
            capture_output=capture,
            text=True,
        )
    else:
        python = get_python()
        result = subprocess.run(
            python + " -c " + cmd if cmd else python.split() + cmd.split(),
            cwd=PROJECT_ROOT,
            env=env,
            capture_output=capture,
            text=True,
            shell=True,
        )

    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
    return result.returncode


def cmd_setup(args):
    """Initialize project configuration."""
    import configparser

    if args.reset and not args.force:
        print("ERROR: --reset requires --force to confirm")
        print("This will overwrite existing configuration!")
        return 1

    config_file = PROJECT_ROOT / ".env"
    existing_vars = {}

    if config_file.exists() and not args.reset:
        print(f"Loading existing config from {config_file}")
        configparser = configparser.ConfigParser()
        configparser.read(config_file)
        if configparser.has_section("settings"):
            for key, value in configparser["settings"].items():
                existing_vars[key.upper()] = value
    elif config_file.exists() and args.reset:
        print("Resetting configuration (existing file will be backed up)")
        backup_file = config_file.with_suffix(".env.backup")
        config_file.rename(backup_file)
        print(f"Backed up to {backup_file}")

    jwt_secret = existing_vars.get("JWT_SECRET") or secrets.token_urlsafe(32)
    qdrant_host = existing_vars.get("QDRANT_HOST", "localhost")
    falkordb_host = existing_vars.get("FALKORDB_HOST", "localhost")
    llm_provider = existing_vars.get("LLM_PROVIDER", "openrouter")
    llm_api_key = existing_vars.get("LLM_API_KEY", "")

    if args.generate_secrets:
        jwt_secret = secrets.token_urlsafe(32)
        print("Generated new JWT_SECRET")
    elif args.reset:
        jwt_secret = secrets.token_urlsafe(32)
        print("Generated fresh JWT_SECRET for reset")
    else:
        print("Using existing JWT_SECRET")

    env_content = f"""# Engineering Intelligence System - Environment Configuration
# Generated by eis.py setup

[settings]
JWT_SECRET={jwt_secret}
QDRANT_HOST={qdrant_host}
FALKORDB_HOST={falkordb_host}
LLM_PROVIDER={llm_provider}
LLM_API_KEY={llm_api_key}

# Development defaults
LOG_LEVEL=INFO
DEBUG=false
"""

    with open(config_file, "w") as f:
        f.write(env_content)

    print(f"✓ Configuration written to {config_file}")
    print(f"  JWT_SECRET: {'*' * 20}{jwt_secret[-4:]}")
    print(f"  QDRANT_HOST: {qdrant_host}")
    print(f"  FALKORDB_HOST: {falkordb_host}")
    print(f"  LLM_PROVIDER: {llm_provider}")

    if args.install_deps:
        print("\nInstalling dependencies...")
        install_result = subprocess.run(
            [UV, "sync"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        if install_result.returncode == 0:
            print("✓ Dependencies installed")
        else:
            print(f"⚠ Install warning: {install_result.stderr[:200]}")

    print("\n✓ Setup complete!")
    print("  Run './eis.py start' to start the server")
    return 0


def cmd_start(args):
    """Start the API server."""
    host = args.host or "0.0.0.0"
    port = args.port or "8000"

    print(f"Starting API at http://{host}:{port}")
    cmd = [get_python(), "-m", "uvicorn", "api.main:app", "--host", host, "--port", port]
    if args.reload:
        cmd.append("--reload")
    return subprocess.run(cmd, cwd=PROJECT_ROOT).returncode


def cmd_test(args):
    """Run tests."""
    if args.file:
        cmd = f"-m pytest tests/{args.file} -v"
    elif args.keyword:
        cmd = f'-m pytest -k "{args.keyword}" -v'
    elif args.unit:
        cmd = "-m pytest tests/test_core.py tests/test_agents.py -v"
    else:
        cmd = "-m pytest tests/ -v"

    print(f"Running: {cmd}")
    return subprocess.run(
        f"{get_python()} {cmd}",
        cwd=PROJECT_ROOT,
        shell=True,
    ).returncode


def cmd_shell(args):
    """Start an interactive Python shell."""
    print("Starting Python shell... (Ctrl+D to exit)")
    return subprocess.run(
        [get_python()],
        cwd=PROJECT_ROOT,
    ).returncode


def cmd_install(args):
    """Install dependencies."""
    return subprocess.run(
        [UV, "pip", "install", "-r", "requirements.txt"],
        cwd=PROJECT_ROOT,
    ).returncode


def cmd_check(args):
    """Run linting and type checking."""
    print("Running ruff...")
    result = subprocess.run(
        [get_python(), "-m", "ruff", "check", "."],
        cwd=PROJECT_ROOT,
        capture_output=True,
    )
    if result.returncode == 0:
        print("✓ Ruff: OK")

    print("Running mypy...")
    result = subprocess.run(
        [get_python(), "-m", "mypy", "core/", "--ignore-missing-imports"],
        cwd=PROJECT_ROOT,
        capture_output=True,
    )
    if result.returncode == 0:
        print("✓ Mypy: OK")

    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Engineering Intelligence System CLI", prog="eis.py"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # start command
    start_parser = subparsers.add_parser("start", help="Start the API server")
    start_parser.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    start_parser.add_argument("--port", default="8000", help="Port to bind to")
    start_parser.add_argument("--reload", action="store_true", help="Enable auto-reload")

    # test command
    test_parser = subparsers.add_parser("test", help="Run tests")
    test_parser.add_argument("--file", help="Specific test file (e.g., test_core.py)")
    test_parser.add_argument("--keyword", help="Test keyword to filter")
    test_parser.add_argument("--unit", action="store_true", help="Run unit tests only")

    # shell command
    shell_parser = subparsers.add_parser("shell", help="Start Python shell")

    # install command
    install_parser = subparsers.add_parser("install", help="Install dependencies")

    # check command
    check_parser = subparsers.add_parser("check", help="Run linting and type checking")

    # setup command
    setup_parser = subparsers.add_parser("setup", help="Initialize project configuration")
    setup_parser.add_argument(
        "--reset", action="store_true", help="Reset configuration (requires --force)"
    )
    setup_parser.add_argument(
        "--force", action="store_true", help="Force reset without confirmation"
    )
    setup_parser.add_argument(
        "--generate-secrets", action="store_true", help="Generate new JWT_SECRET"
    )
    setup_parser.add_argument(
        "--install-deps", action="store_true", help="Install dependencies after setup"
    )

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 0

    commands = {
        "start": cmd_start,
        "api": cmd_start,
        "test": cmd_test,
        "shell": cmd_shell,
        "install": cmd_install,
        "check": cmd_check,
        "setup": cmd_setup,
    }

    if args.command in ("setup", "start", "api"):
        return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
