apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eis-prod

bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: "Always"
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
    target:
      kind: Ingress

commonLabels:
  app.kubernetes.io/environment: production