apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eis-api-network-policy
  namespace: eis
  labels:
    app.kubernetes.io/name: eis-api
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eis-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: eis
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 6333
        - protocol: TCP
          port: 7379