apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eis-api-pdb
  namespace: eis
  labels:
    app.kubernetes.io/name: eis-api
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eis-api