from ui.knowledge import (
    ComponentType,
    UIComponent,
    UIComponentKnowledge,
    UIService,
    get_ui_knowledge_registry,
)


def _create_sap_knowledge() -> UIComponentKnowledge:
    knowledge = UIComponentKnowledge(
        domain_id="sap",
        display_name="SAP UI5/Fiori",
        supported_element_types=[
            "button",
            "input",
            "select",
            "table",
            "form",
            "card",
            "navigation",
            "header",
            "footer",
            "tab",
            "chart",
            "filter",
        ],
    )

    components = [
        UIComponent(
            component_id="comp-sap-m-table",
            name="sap.m.Table",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["table"],
            properties=[
                "items",
                "columns",
                "growing",
                "mode",
                "fixedLayout",
                "busy",
                "swipeContent",
            ],
            events=["itemPress", "selectionChange", "growing", "updateFinished", "beforeRendering"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.Table",
            complexity=2,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-ui-table",
            name="sap.ui.table.Table",
            library="sap.ui.table",
            component_type=ComponentType.CONTROL,
            supported_element_types=["table"],
            properties=[
                "rows",
                "columns",
                "visibleRowCount",
                "selectionMode",
                "enableColumnFreeze",
                "threshold",
            ],
            events=["rowSelectionChange", "columnResize", "cellClick", "rowsUpdated"],
            documentation_url="https://ui5.sap.com/#/api/sap.ui.table.Table",
            complexity=3,
            metadata={"deprecated": False, "responsive": False},
        ),
        UIComponent(
            component_id="comp-sap-m-button",
            name="sap.m.Button",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["button"],
            properties=["text", "icon", "type", "enabled", "width", "tooltip"],
            events=["press", "tap"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.Button",
            complexity=1,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-m-input",
            name="sap.m.Input",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["input"],
            properties=[
                "value",
                "placeholder",
                "type",
                "enabled",
                "editable",
                "required",
                "maxLength",
            ],
            events=["change", "liveChange", "submit", "valueHelpRequest"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.Input",
            complexity=1,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-m-select",
            name="sap.m.Select",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["select", "dropdown"],
            properties=["items", "selectedKey", "enabled", "editable", "forceSelection"],
            events=["change", "selectionChange"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.Select",
            complexity=1,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-ui-layout-form",
            name="sap.ui.layout.form.SimpleForm",
            library="sap.ui.layout",
            component_type=ComponentType.CONTROL,
            supported_element_types=["form"],
            properties=[
                "title",
                "layout",
                "editable",
                "maxContainerCols",
                "emptySpan",
                "labelSpan",
            ],
            events=[],
            documentation_url="https://ui5.sap.com/#/api/sap.ui.layout.form.SimpleForm",
            complexity=2,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-m-page",
            name="sap.m.Page",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["navigation", "header", "footer"],
            properties=["title", "showHeader", "showFooter", "showNavButton", "backgroundDesign"],
            events=["navButtonPress"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.Page",
            complexity=1,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-f-dynamicpage",
            name="sap.f.DynamicPage",
            library="sap.f",
            component_type=ComponentType.CONTROL,
            supported_element_types=["navigation"],
            properties=[
                "title",
                "headerContent",
                "showFooter",
                "preserveHeaderState",
                "backgroundDesign",
            ],
            events=["toggleHeaderState"],
            documentation_url="https://ui5.sap.com/#/api/sap.f.DynamicPage",
            complexity=3,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-m-icontabbar",
            name="sap.m.IconTabBar",
            library="sap.m",
            component_type=ComponentType.CONTROL,
            supported_element_types=["tab"],
            properties=["items", "selectedKey", "headerMode", "expandable", "applyContentDensity"],
            events=["select", "tabSelect"],
            documentation_url="https://ui5.sap.com/#/api/sap.m.IconTabBar",
            complexity=2,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-makit-chart",
            name="sap.makit.Chart",
            library="sap.makit",
            component_type=ComponentType.CONTROL,
            supported_element_types=["chart"],
            properties=["category", "values", "rows", "type", "showTotalLabel", "dimensionColor"],
            events=["dataSelection", "tooltipDisplay"],
            documentation_url="https://ui5.sap.com/#/api/sap.makit.Chart",
            complexity=3,
            metadata={"deprecated": True, "responsive": False},
        ),
        UIComponent(
            component_id="comp-sap-ui-comp-filterbar",
            name="sap.ui.comp.filterbar.FilterBar",
            library="sap.ui.comp",
            component_type=ComponentType.CONTROL,
            supported_element_types=["filter"],
            properties=["filterGroupItems", "search", "clear", "restore", "useToolbar"],
            events=["search", "clear", "afterVariantLoad"],
            documentation_url="https://ui5.sap.com/#/api/sap.ui.comp.filterbar.FilterBar",
            complexity=3,
            metadata={"deprecated": False, "responsive": True},
        ),
        UIComponent(
            component_id="comp-sap-f-card",
            name="sap.f.Card",
            library="sap.f",
            component_type=ComponentType.CONTROL,
            supported_element_types=["card"],
            properties=["header", "content", "manifest", "subtitles"],
            events=["cardAction"],
            documentation_url="https://ui5.sap.com/#/api/sap.f.Card",
            complexity=2,
            metadata={"deprecated": False, "responsive": True},
        ),
    ]
    for comp in components:
        knowledge.components[comp.name] = comp

    services = [
        UIService(
            service_id="svc-xsuaa",
            name="XSUAA",
            service_type="security",
            capabilities=["authentication", "authorization", "token-validation"],
            documentation_url="https://help.sap.com/docs/xsuaa-service",
        ),
        UIService(
            service_id="svc-destination",
            name="Destination",
            service_type="connectivity",
            capabilities=["destination-management", "proxy", "on-premise-connectivity"],
            documentation_url="https://help.sap.com/docs/destination-service",
        ),
        UIService(
            service_id="svc-html5-repo",
            name="HTML5 Application Repository",
            service_type="storage",
            capabilities=["static-hosting", "ui-deployment", "version-management"],
            documentation_url="https://help.sap.com/docs/html5-application-repository-service",
        ),
    ]
    for svc in services:
        knowledge.services[svc.name] = svc

    return knowledge


def _register_sap_knowledge():
    reg = get_ui_knowledge_registry()
    reg.register(_create_sap_knowledge())


_register_sap_knowledge()
