"""
Models Module - Pydantic schemas for the system.

Exports: IR, Graph, Retrieval, and MCP schemas.
"""

from models.graph import (
    GraphEdge,
    GraphEdgeType,
    GraphNode,
    GraphNodeType,
    GraphQuery,
    SubgraphResult,
)
from models.graphrag import (
    Community,
    CommunityResponse,
    EntityNode,
    EntitySearchRequest,
    EntitySearchResponse,
    EntityType,
    GraphRAGConfig,
    GraphRAGQueryRequest,
    GraphRAGQueryResponse,
    GraphRAGStatsResponse,
    RelationshipEdge,
    RelationshipSearchRequest,
    RelationshipSearchResponse,
    RelationshipType,
)
from models.ir import (
    UIIR,
    ArchitectureIR,
    ArtifactStatus,
    ArtifactType,
    CodeIR,
    ComponentType,
    DocumentIR,
    IRCollection,
    IRNode,
    Technology,
)
from models.mcp import (
    MCP_TOOLS,
    MCPRequest,
    MCPResponse,
    MCPToolCall,
    MCPToolDefinition,
)
from models.retrieval import (
    CodeEntity,
    Document,
    Metric,
    RetrievalRequest,
    RetrievalResult,
    RetrievalSource,
    SearchType,
    TelemetryEvent,
    Ticket,
)

__all__ = [
    "IRNode",
    "ArchitectureIR",
    "UIIR",
    "CodeIR",
    "DocumentIR",
    "IRCollection",
    "ArtifactType",
    "ArtifactStatus",
    "ComponentType",
    "Technology",
    "GraphNode",
    "GraphEdge",
    "GraphQuery",
    "SubgraphResult",
    "GraphNodeType",
    "GraphEdgeType",
    "RetrievalSource",
    "SearchType",
    "Document",
    "CodeEntity",
    "Ticket",
    "TelemetryEvent",
    "Metric",
    "RetrievalResult",
    "RetrievalRequest",
    "MCPRequest",
    "MCPResponse",
    "MCPToolDefinition",
    "MCPToolCall",
    "MCP_TOOLS",
    "EntityType",
    "RelationshipType",
    "EntityNode",
    "RelationshipEdge",
    "Community",
    "GraphRAGConfig",
    "GraphRAGQueryRequest",
    "GraphRAGQueryResponse",
    "EntitySearchRequest",
    "EntitySearchResponse",
    "RelationshipSearchRequest",
    "RelationshipSearchResponse",
    "CommunityResponse",
    "GraphRAGStatsResponse",
]
