"""
Models Module - Pydantic schemas for the system.

Exports: IR, Graph, Retrieval, and MCP schemas.
"""

from models.ir import (
    IRNode,
    ArchitectureIR,
    UIIR,
    CodeIR,
    DocumentIR,
    IRCollection,
    ArtifactType,
    ArtifactStatus,
    ComponentType,
    Technology,
)
from models.graph import (
    GraphNode,
    GraphEdge,
    GraphQuery,
    SubgraphResult,
    GraphNodeType,
    GraphEdgeType,
)
from models.retrieval import (
    RetrievalSource,
    SearchType,
    Document,
    CodeEntity,
    Ticket,
    TelemetryEvent,
    Metric,
    RetrievalResult,
    RetrievalRequest,
)
from models.mcp import (
    MCPRequest,
    MCPResponse,
    MCPToolDefinition,
    MCPToolCall,
    MCP_TOOLS,
)
from models.graphrag import (
    EntityType,
    RelationshipType,
    EntityNode,
    RelationshipEdge,
    Community,
    GraphRAGConfig,
    GraphRAGQueryRequest,
    GraphRAGQueryResponse,
    EntitySearchRequest,
    EntitySearchResponse,
    RelationshipSearchRequest,
    RelationshipSearchResponse,
    CommunityResponse,
    GraphRAGStatsResponse,
)


__all__ = [
    "IRNode",
    "ArchitectureIR",
    "UIIR",
    "CodeIR",
    "DocumentIR",
    "IRCollection",
    "ArtifactType",
    "ArtifactStatus",
    "ComponentType",
    "Technology",
    "GraphNode",
    "GraphEdge",
    "GraphQuery",
    "SubgraphResult",
    "GraphNodeType",
    "GraphEdgeType",
    "RetrievalSource",
    "SearchType",
    "Document",
    "CodeEntity",
    "Ticket",
    "TelemetryEvent",
    "Metric",
    "RetrievalResult",
    "RetrievalRequest",
    "MCPRequest",
    "MCPResponse",
    "MCPToolDefinition",
    "MCPToolCall",
    "MCP_TOOLS",
    "EntityType",
    "RelationshipType",
    "EntityNode",
    "RelationshipEdge",
    "Community",
    "GraphRAGConfig",
    "GraphRAGQueryRequest",
    "GraphRAGQueryResponse",
    "EntitySearchRequest",
    "EntitySearchResponse",
    "RelationshipSearchRequest",
    "RelationshipSearchResponse",
    "CommunityResponse",
    "GraphRAGStatsResponse",
]
